language: node_js
node_js:
  - '0.10'
env:
  global:
    - secure: ZUzvlbTZYFO8w0Rc3GGYhQ++UVePyJCZBzPUm34UrzhSCHPw9lUkPeXtuk+aefoyoSwGDGosfo9X0ALFJmdS9KHd11vT5qwrIHIiZZ/rZIRwMAWVsQ9QjQNBX+xFnM232kTCV8kfi4X2HnFvJbvjbrD45zicFi4TLPF+ZlUAqEc=
    - secure: cHkQrsJWWVQOjnoNstyqMKOOAddKILZHHCp3Hc8C07lSKHOhz7AKI1dtklkGPBNoOTU3avaDKFP+Q7Wr2Hlfnzwy8qNO2/uPpQIL4nMgxcIKNb4FajUAuBkN4ny26PMyAASaOhznuI5KUJZdW3gw/Ff+zkgENY8q3gJD6E4ci+s=
  - BROWSER_NAME=chrome BROWSER_VERSION=latest
  - BROWSER_NAME=chrome BROWSER_VERSION=29
  - BROWSER_NAME=firefox BROWSER_VERSION=latest
  - BROWSER_NAME=opera BROWSER_VERSION=latest
  - BROWSER_NAME=safari BROWSER_VERSION=latest
  - BROWSER_NAME=safari BROWSER_VERSION=7
  - BROWSER_NAME=safari BROWSER_VERSION=6
  - BROWSER_NAME=safari BROWSER_VERSION=5
  - BROWSER_NAME=ie BROWSER_VERSION=11
  - BROWSER_NAME=ie BROWSER_VERSION=10
  - BROWSER_NAME=ie BROWSER_VERSION=9
